[package]
name = "rlr"
version = "0.1.0"
authors = ["amfl <amfl@none.none>"]

[dependencies]

serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
pancurses = "0.16"
rand = "*"

specs = "0.10"

log = "*"
env_logger = "*"
